/*****************************************************************************
    Copyright (c) 2004 by Cisco Systems, Inc.
    All rights reserved.

    File: clkrec.c

    Date        Who     Modification
    --------    ------  ------------------------------------------------------
    02-02-05    ytse    Created.

    This program perform clock recovery simulation for DOCSIC timestamps.
    It takes as input a file containing the timestamp info
    (generated by tsgen.c), an another file for network jitter info.
    The network delay is taken as "jitter * gain + offset".
    The program produces an output file in the same format as timestamp
    info file.
    The jitter info file will be reuse if it contains less entries as
    in the input timestamp file.

*****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include "param.h"


#define MAX_TS                  ((double) 4294967296.0)
#define REF_CLK_FREQ            ((double) 10240000.)


typedef unsigned int uint;


// Clock recovery related variables
//
char ts_file[128];
char jit_file[128];
char out_file[128];
char stat_file[128];
FILE *ts_fp;
FILE *jit_fp;
FILE *out_fp;
FILE *stat_fp;

float jit_gain;                 // gain for network jitter
float delay_offset;             // offset for network delay
float lpf_par;                  // loop filter parameter
float loop_gain;                // loop gain
float max_freq_adj;             // max frequency adjustment

uint ts_idx;
uint ts;                        // timestamp value
float jitter;                   // jitter info
float delay;                    // network delay
uint send_time;                 // source send time of timestamp
uint arvl_time;                 // arrival time of timestamp
uint prev_arvl_time;            // arrival time of previous timestamp
uint prev_ts;                   // previous timestamp value
uint ts_inc;                    // increment between current and previous
                                // timestamps
double est_drift;               // estimated drift in phase from previous
                                // timestamps
int in_tbo;                     // input time base offset
double est_tbo;                 // estimated time base ofset
double err_tbo;                 // error in time base offset
double norm_err_tbo;            // normalized time base offset error
double flt_err_tbo;             // filtered time base offset error
double freq_adj;                // clock frequency adjustment (in ratio)
uint out_time;                  // output time
uint prev_out_time;
uint out_ts;                    // output timestamp value
uint prev_out_ts;
double ts_jitter;
int latency;
int phase_err;


void wrap_min_max (double *x)
{
    if (*x < 0.0) {
        *x += MAX_TS;
    } else if (*x >= MAX_TS) {
        *x -= MAX_TS;
    }
}


// Clock recovery for timestamp
//
void clkrec_ts (uint arvl_time, uint ts)
{
    double tmp;

    in_tbo = (int)(ts - arvl_time);

    if (ts_idx == 0) {
        // For 1st timestamp
        est_tbo = in_tbo;
        err_tbo = 0.;
        flt_err_tbo = 0.;
        freq_adj = 0.;

    } else {
        ts_inc = (int)(ts - prev_ts);

        // Drift prediction
        est_drift = ts_inc * freq_adj;
        est_tbo += est_drift;

        // Differencing
        err_tbo = in_tbo - est_tbo;

        // Normalization
        norm_err_tbo = err_tbo / ts_inc;
    
        // Loop filter
        tmp = norm_err_tbo - flt_err_tbo;
        flt_err_tbo += tmp * lpf_par;

        // Convert to error frequency
        freq_adj = loop_gain * flt_err_tbo;

        // Clamping
        if (freq_adj > max_freq_adj) {
            freq_adj = max_freq_adj;
        } else if (freq_adj < -max_freq_adj) {
            freq_adj = -max_freq_adj;
        } 
    }

    // Compute output timestamp
    out_time = arvl_time;        // assume zero system delay
    tmp = out_time + est_tbo;
    wrap_min_max(&tmp);
    out_ts = tmp;

    // Update
    ts_idx++;
    prev_ts = ts;
}


int main(int argc, char **argv)
{
    Param par;
    int n;
    double temp;

    if (argc > 1) {
        beginParam(&par, argc, argv);
    } else {
        readParam(&par, "clkrec.par");
    }

    getStringParam(&par, "Input timestamp filename", ts_file, "in.ts");
    getStringParam(&par, "Network jitter filename", jit_file, "jitter.dat");
    getFloatParam(&par, "Jitter gain", &jit_gain, 1.);
    getFloatParam(&par, "Delay offset", &delay_offset, 0.);
    getFloatParam(&par, "Loop filter parameter", &lpf_par, 0.0001);
    getFloatParam(&par, "PLL loop gain", &loop_gain, 0.0001);
    getFloatParam(&par, "Max frequency adjustment (Hz)", &max_freq_adj, 100);
    getStringParam(&par, "Output timestamp filename", out_file, "out.stat");
    getStringParam(&par, "Output statistic filename", stat_file, "out.stat");
    endParam(&par);

    ts_fp = fopen(ts_file, "r");
    if (ts_fp == NULL) {
        printf("Error: failed to open input timestamp file %s\n", ts_file);
        exit(-1);
    }

    jit_fp = fopen(jit_file, "r");
    if (jit_fp == NULL) {
        printf("Error: failed to open input delay file %s\n", jit_file);
        exit(-1);
    }

    out_fp = fopen(out_file, "w");
    if (out_fp == NULL) {
        printf("Error: failed to open output timestamp file %s\n", out_file);
        exit(-1);
    }

    stat_fp = fopen(stat_file, "w");
    if (stat_fp == NULL) {
        printf("Error: failed to open output statistics file %s\n", stat_file);
        exit(-1);
    }

    while (1) {
        // Read timestamp info
        n = fscanf(ts_fp, "%d %d", &send_time, &ts);
        if (n < 2)  break;

        // Read jitter 
        n = fscanf(jit_fp, "%f", &jitter); 
        if (n < 1) {
            fseek(jit_fp, 0, SEEK_SET);
            n = fscanf(jit_fp, "%f", &jitter); 
            if (n < 1) {
                printf("Error: failed to read network delay\n");
                break;
            }
        }

        // Calculate arrival time
        delay = jitter * jit_gain + delay_offset;
        temp = (double)send_time + delay;
        wrap_min_max(&temp);
        arvl_time = (uint)temp;

        // Make sure there is no reversal of time
        if ((int)(arvl_time - prev_arvl_time) < 0) {
            arvl_time = prev_arvl_time;
        } else {
            prev_arvl_time = arvl_time;
        }

        // Perform clock recovery
        clkrec_ts(arvl_time, ts);

        // Compute phase error
        latency = (int)(out_time - send_time);
        phase_err = (int)(ts - out_ts) + latency;

        // Compute timestamp jitter
        if (ts_idx > 0) {
            ts_jitter = ((int)(out_ts - prev_out_ts)
                         - (int)(out_time - prev_out_time)) / REF_CLK_FREQ;
//            ts_jitter = (int)(out_ts - prev_out_ts) - (int)(out_time - prev_out_time);
//            ts_jitter /= REF_CLK_FREQ;
        }
        if (ts_jitter < 0) {
            ts_jitter = -ts_jitter;
        }

        // Output timestamp info:
        //   TS value, send time, arrival time, delay
        fprintf(out_fp, "%d %d %d %d\n", ts, send_time, arvl_time, (uint)delay);

        // Output statistics:
        //   err_tbo (ms), flt_err_tbo (ms), freq_adj (ppm),
        //   phase_err (ms), jitter (ns)
        fprintf(stat_fp, "%9g %9g %9g %9g %9g\n",
                err_tbo*1e3/REF_CLK_FREQ, flt_err_tbo, freq_adj*1e6,
                phase_err*1e3/REF_CLK_FREQ, ts_jitter*1e9);

        // Update
        prev_out_time = out_time;
        prev_out_ts = out_ts;
    }

    fclose(ts_fp);
    fclose(jit_fp);
    fclose(out_fp);
    fclose(stat_fp);
    return 0;
}
