/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */


void
echo_prog_2(host)
	char *host;
{
	CLIENT *clnt;
	void  *result_1;
	char *  echoproc_null_2_arg;
	result  *result_2;
	arg  echoproc_echo_2_arg;

#ifndef	DEBUG
	clnt = clnt_create(host, ECHO_PROG, ECHO_VERS, "netpath");
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif	/* DEBUG */

	result_1 = echoproc_null_2((void *)&echoproc_null_2_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	result_2 = echoproc_echo_2(&echoproc_echo_2_arg, clnt);
	if (result_2 == (result *) NULL) {
		clnt_perror(clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy(clnt);
#endif		/* DEBUG */
}


main(argc, argv)
	int argc;
	char *argv[];
{
	char *host;

	if (argc < 2) {
		printf("usage:  %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	echo_prog_2(host);
}
