/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>

void *
echoproc_null_2(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{
	static char * result;

	/*
	 * insert server code here
	 */
        printf("Echo Null procedure being called.\n");

	return((void *) &result);
}

result *
echoproc_echo_2(argp, rqstp)
	arg *argp;
	struct svc_req *rqstp;
{
	static result  result;

	/*
	 * insert server code here
	 */
        printf("Echo procedure being called:\n");
        printf("Args: count %d, Input [%s]\n", argp->count, argp->in);
        sprintf(result.out, "Echo result: %s", argp->in);

	return (&result);
}
