/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define	_ECHO_H_RPCGEN

#include <rpc/rpc.h>

struct arg {
	char *in;
	int count;
};
typedef struct arg arg;

struct result {
	char *out;
};
typedef struct result result;

#define	ECHO_PROG	0x20000000
#define	ECHO_VERS	2
#define	ECHOPROC_NULL	0
extern  void * echoproc_null_2();
#define	ECHOPROC_ECHO	1
extern  result * echoproc_echo_2();
extern int echo_prog_2_freeresult();

/* the xdr functions */
extern bool_t xdr_arg();
extern bool_t xdr_result();

#endif /* !_ECHO_H_RPCGEN */
