/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "echo.h"

bool_t
xdr_arg(xdrs, objp)
	register XDR *xdrs;
	arg *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->in, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_result(xdrs, objp)
	register XDR *xdrs;
	result *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->out, ~0))
		return (FALSE);
	return (TRUE);
}
