/*****************************************************************************
    Copyright (c) 2004 by Cisco Systems, Inc.
    All rights reserved.

    File: clkrec.c

    Date        Who     Modification
    --------    ------  ------------------------------------------------------
    07-20-04    ytse    Created.

    This program reads in packet timing information generated by datagen.c
    and perform clock recovery simulation.

    Input file format:
        ref_time  timestamp_flag  timestamp  in_time

    Output file format:
        ref_time  timestamp_flag  timestamp  in_time
        arvl_time  dj_arvl_time  out_time  out_timestamp

    Note:
      - ref_time and out_time are in micro seconds (us).
*****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include "param.h"


typedef unsigned int uint;

char in_file[128];
char out_file[128];
float clk_freq;
float samp_itvl;
float djf_par;
float lpf_par;
float loop_gain;
float sys_delay;
FILE* in_fp;
FILE* out_fp;

uint ref_time;
uint ts_flag;
uint cur_ts;
uint in_time;

uint arvl_time;
double dj_arvl_time;
uint prev_arvl_time;    // arrival time of previous packet
double in_tpi;          // input TP interval
double dj_tpi;          // dejittered TP interval

// Clock recovery related variables
int tp_found;           // whether the 1st TP has been found
int ts_found;           // whether the 1st timestamp has been found

uint period_idx;        // input period index
uint tp_idx;            // TP index
uint ts_idx;            // timestamp index
uint prev_ts_tp_idx;    // TP index of the previous timestamp
uint prev_ts;           // previous timestamp value
uint ts_tp_idx_inc;     // increment between TP index containing
                        //   current and previous timestamps
uint ts_inc;            // increment between current and previous timestamps
double dj_tbo;          // time base offset between timestamp
double freq_adj;        // clock frequency adjustment (in ratio)
double tbo_drift;       // drift in phase btw previous and current timestamps
double est_tbo;         // estimated time base ofset
double err_tbo;         // estimation error in time base offset
                        //   and dejittered arrival time
double norm_err_tbo;    // normalized time base offset error
double flt_err_tbo;     // filtered time base offset error

uint out_ts;            // output timestamp
uint out_time;          // delivery time



void dejitter_filter ()
{
    double diff;

    if (!tp_found) {
        dj_arvl_time = arvl_time;
        tp_found = 1;

    } else {
        in_tpi = arvl_time - prev_arvl_time;

        diff = in_tpi - dj_tpi;
        dj_tpi += diff * djf_par;

        dj_arvl_time += dj_tpi;
        prev_arvl_time = arvl_time;
    }
}


void clkrec_ts_tp ()
{
    double diff;

    dejitter_filter();

    if (!ts_found) {
        // For 1st timestamp
        dj_tbo = cur_ts - dj_arvl_time;
        est_tbo = dj_tbo;
        err_tbo = 0.;
        ts_found = 1;

    } else {
        ts_inc = cur_ts - prev_ts;
        ts_tp_idx_inc = tp_idx = prev_ts_tp_idx;
        dj_tbo = cur_ts - dj_arvl_time;

        // Drift prediction
        tbo_drift = ts_inc * freq_adj;
        est_tbo += tbo_drift;

        // Differencing
        err_tbo = dj_tbo - est_tbo;

#if 1
        // Normalization
        norm_err_tbo = err_tbo / ts_inc;
#else
        norm_err_tbo = err_tbo;
#endif

        // Loop filter
        diff = norm_err_tbo - flt_err_tbo;
        flt_err_tbo += diff * lpf_par;

        // Convert to error frequency
        freq_adj = loop_gain * flt_err_tbo;

        // Clamping (TBD)
    }

    // Compute delivery time
    out_time = arvl_time + sys_delay;

    // Compute output timestamp
    out_ts = cur_ts + est_tbo;
}


void clkrec_non_ts_tp ()
{
    dejitter_filter();
    out_time = arvl_time + sys_delay;
}


int main(int argc, char **argv)
{
    Param par;
    int status;
    uint dj_arvl_time2;

    if (argc > 1) {
        beginParam(&par, argc, argv);
    } else {
        readParam(&par, "clkrec.par");
    }

    getStringParam(&par, "Input filename", in_file, "tp_info.dat");
    getFloatParam(&par, "Reference clock frequency (Hz)", &clk_freq, 10240000.);
    getFloatParam(&par, "Input sampling interval (us)", &samp_itvl, 100);
    getFloatParam(&par, "Dejittering filter parameter", &djf_par, 0.0004);
    getFloatParam(&par, "Loop filter parameter", &lpf_par, 0.00001);
    getFloatParam(&par, "PLL loop gain", &loop_gain, 0.0001);
    getFloatParam(&par, "System latency (us)", &sys_delay, 500.);
    getStringParam(&par, "Output filename", out_file, "tp_info.out");
    endParam(&par);

    in_fp = fopen(in_file, "r");
    if (in_fp == NULL) {
        printf("Error: failed to open input file %s\n", in_file);
        exit(-1);
    }

    out_fp = fopen(out_file, "w");
    if (out_fp == NULL) {
        printf("Error: failed to open output file %s\n", out_file);
        exit(-1);
    }

    sys_delay = sys_delay * clk_freq / 1000000.;
    samp_itvl = samp_itvl * clk_freq / 1000000.;

    period_idx = 0;
    arvl_time = samp_itvl;
    tp_idx = ts_idx = 0;
    tp_found = ts_found = 0;
    dj_tpi = 0;

    while (1) {
        status = fscanf(in_fp, "%d %d %d %d",
                        &ref_time, &ts_flag, &cur_ts, &in_time);
        if (status <= 0)  break;

        while (in_time > arvl_time) {
            period_idx++;
            arvl_time += samp_itvl;
            printf("Period %d: freq_adj %g\n", period_idx, freq_adj);
        }

        if (ts_flag) {
            clkrec_ts_tp();
            ts_idx++;
        } else {
            clkrec_non_ts_tp();
        }

        dj_arvl_time2 = dj_arvl_time;

        fprintf(out_fp, "%7d %1d %7d %7d %7d %7d %7d %7d\n",
               ref_time, ts_flag, cur_ts, in_time, arvl_time,
               dj_arvl_time2, out_time, (ts_flag? out_ts : 0));
        tp_idx++;
    }

    fclose(in_fp);
    fclose(out_fp);
    return 0;
}
