#! /bin/csh

cd /vob/ios/sys

echo "Making dependencies..."
/router/bin/make -j8 dependencies

echo "Building image..."
make -j8 -k -C /vob/ios/sys/obj-ppc-rfgw RFGW_EMBEDDED_BUILD=1 GDB_FLAG=-g rfgw-entservices-mz

