/*
 * This file represents the unit test module generated by /auto/ses/repository/sesut.3.4.1/sesut/scripts/ses_iosutgen
 * based on the unit test model described in /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut.
 * Do not edit this file. Edit the model file /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut.
 * This file contains the the function sesut_ermi_r_fsmtest. This function
 * is the unit test. Execute this function. This function can have
 * parameters. Values for parameters can be received via CLI.
 * This file also contains code to define a subsystem and a parse
 * chain to define a CLI to execute the unit test.
 * The function can be called from other modules in the image.
 * Include the header file that is also generated.
 * Built in /vob/ios.sys7/sys/obj-sp-unixrp
 *     at Sat Jan 17 00:01:06 2009 UTC by dechen
 * Send questions to ses-support.
 */

#include "../testtools/ermi_r_fsmtest.sesut.h"

char sesut_ermi_r_fsmtest_selected_node [256];

               /* /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut:140 */
# 141 "/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut"


















#include "master.h"
#include "/vob/ios/sys/obj-sp-unixrp/ermi_r_protocol_def.h"
#include "/vob/ios/sys/obj-sp-unixrp/ermi_r_errp_fsm.h"
#include "/vob/ios/sys/obj-sp-unixrp/ermi_r_main.h"

/* If we have assert use it. Else create one. */
#ifndef assert
#define assert(EXP) if(!(EXP)){buginf("Assert failure at %d in file %s\n",__LINE__,__FILE__);}
#endif

#ifndef sesut_assert
#define sesut_assert(EXP) if(!(EXP)){buginf("ABORT: assert failed at %s(%d)\n",__FILE__,__LINE__);\
sesut_ermi_r_fsmtest_testfail("ABORT: assert failed at file %s (%d)\n",__FILE__,__LINE__);return;}
#endif


/* sesut_ermi_r_fsmtest is the unit test */
void sesut_ermi_r_fsmtest(addrtype* peer_addr) {
               /* /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut:163 */
# 164 "/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut"
    











































extern ermi_r_master_t ermi_r_master;
pid_t ermi_r_test_pid;
list_element *elem;
ermi_r_neighbor_t *nbr;


    sesut_ermi_r_fsmtest_startoftest();
              /* Entry code for start node StartNode*/
               /* /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut:213 */
# 213 "/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut"
               sesut_ermi_r_fsmtest_graph_entry_action(0);
# 214 "/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut"
ermi_r_test_pid = process_create(ermi_r_main_process,
	                        "ERMI_R test process",
				NORMAL_STACK, PRIO_NORMAL);
process_sleep_for(2000);
if (peer_addr->ip_addr != 0) {
process_send_message(ermi_r_test_pid, "ERMI_R test process",
	             ERMI_R_MAIN_CONNECT, NULL, 
	             (ipaddrtype)(peer_addr->ip_addr));
process_sleep_for(5000);
FOR_ALL_DATA_IN_LIST(&ermi_r_master.nbr_list, elem, nbr) {
process_send_message(ermi_r_test_pid, "ERMI_R test process",
	             ERMI_R_MAIN_SEND_UPDATE, nbr, 0);
}
}

# 213 "/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut"
    sesut_ermi_r_fsmtest_endoftest();
# 213 "/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut"
}

