/*
 * This file represents the unit test module generated by /auto/ses/repository/sesut.3.4.1/sesut/scripts/ses_iosutgen
 * based on the unit test model described in /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut.
 * Do not edit this file. Edit the model file /vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut.
 * This file contains the the function sesut_ermi_r_fsmtest This function
 * is the unit test. Execute this function. This function can have
 * parameters. Values for parameters can be received via CLI.
 * This file also contains code to define a subsystem and a parse
 * chain to define a CLI to execute the unit test.
 * The function can be called from other modules in the image.
 * Include the header file that is also generated.
 * Built in /vob/ios.sys7/sys/obj-sp-unixrp
 *     at Sat Jan 17 00:01:06 2009 UTC by dechen
 * Send questions to ses-support.
 */
#include "master.h"
#include COMP_INC(ifs, ifs.h)
#include COMP_INC(kernel, subsys.h)
#include COMP_INC(kernel/memory, free_private.h)
#include COMP_INC(kernel/memory, chunk.h)
#include COMP_INC(kernel, clock.h)
#include "../testtools/sesutlib_ios.h"
#include "../testtools/ses_iosutmain.iouso.h"
#include "../testtools/ermi_r_fsmtest.sesut.h"
#include "../parser/macros.h"
#include "../parser/parser_actions.h"
#include "../parser/parser_sesut.h"


/* DTD - Maps function names to codes */
static keyword_options sesut_ermi_r_fsmtest_dtd_functions[] = {
    
    { NULL, NULL, 0 }
};
/* DTD - Maps iterator types to codes */
static keyword_options sesut_ermi_r_fsmtest_dtd_iterators[] = {
    {"complete","Complete enumeration", SESUT_DTD_COMPLETE},
    {"random","Random selection", SESUT_DTD_RANDOM},
    {"onefac","Cover one factor elements", SESUT_DTD_ONEFAC},
    //{"twofac","Cover two factor interactions", SESUT_DTD_TWOFAC},
    //{"onetwofac","Cover one and two factor interactions", SESUT_DTD_ONETWOFAC},
    //{"threefac","Cover three factor interactions", SESUT_DTD_THREEFAC},
    //{"onetwothreefac","Cover one,two and three factor interactions", 
    //                  SESUT_DTD_ONETWOTHREEFAC},
    {NULL,NULL, 0 }
};
/* DTD related variables */
static boolean sesut_ermi_r_fsmtest_dtd_availability=FALSE;
static boolean sesut_ermi_r_fsmtest_dtd_notest=FALSE;
static boolean sesut_ermi_r_fsmtest_dtd_all=FALSE;
/* Delay between each test. Allow for checkheaps checking. */
static unsigned int sesut_ermi_r_fsmtest_dtd_all_delay=0;
static boolean sesut_ermi_r_fsmtest_dtd_singlefn=FALSE;
sesut_ermi_r_fsmtest_dtd_function_codes sesut_ermi_r_fsmtest_dtd_fnid;
sesut_dtd_iteration_types sesut_ermi_r_fsmtest_dtd_iterator;
static long long sesut_ermi_r_fsmtest_dtd_start;
static long long sesut_ermi_r_fsmtest_dtd_next;
static long long sesut_ermi_r_fsmtest_dtd_end;

#define ALTERNATE NONE
#include "../testtools/exec_ermi_r_fsmtest.sesut.h"
LINK_POINT(sesut_ermi_r_fsmtest_exec_command, ALTERNATE);
#undef ALTERNATE

static  parser_extension_request sesut_ermi_r_fsmtest_init_table[] = {
    {PARSE_ADD_EXEC_CMD,  &pname(sesut_ermi_r_fsmtest_exec_command) },
    {PARSE_LIST_END, NULL}
};

/* global scalefactor */
uint sesut_ermi_r_fsmtest_current_scalefactor;

/* Let users access these in their tests */
uint sesut_ermi_r_fsmtest_current_repeatcount;
uint sesut_ermi_r_fsmtest_current_repeatindex;

static uint sesut_ermi_r_fsmtest_trace_status;
static char *sesut_ermi_r_fsmtest_test_name="sesut_ermi_r_fsmtest";
static uint sesut_ermi_r_fsmtest_last_index;
static sesut_ermi_r_fsmtest_time sesut_ermi_r_fsmtest_last_timestamp;
static uint sesut_ermi_r_fsmtest_start_test;
static uint sesut_ermi_r_fsmtest_default_repeatcount;
static ulong sesut_ermi_r_fsmtest_times_cli_used;
static ulong sesut_ermi_r_fsmtest_times_api_used;
/* Number of times the function that executes the test
 * with default values for parameters is invoked.
 */
static ulong sesut_ermi_r_fsmtest_times_defaultapi_used;
static uint sesut_ermi_r_fsmtest_number_of_testinfo_blocks;
/* SESUT_ERMI_R_FSMTEST_MAX_BLOCKS can be defined using -D flag during compilation. */
static boolean sesut_ermi_r_fsmtest_max_testinfo_blocks_defined;
static uint sesut_ermi_r_fsmtest_max_testinfo_blocks;
static chunk_type *sesut_ermi_r_fsmtest_chunk;
static char* sesut_ermi_r_fsmtest_graphLabels[1]=
{
    "Node{StartNode}Line213"/*0*/
};


/* Define various versions of gethrtime() */

#if defined(sparc) || defined(__sparc)
void sesut_ermi_r_fsmtest_print_timer_info(void)
{
    printf("\n\nThe execution times are in nanoseconds.");
    return;
}
#elif defined(__mips) || defined(__mip64)  || defined(__PPC)
static  hrtime_t gethrtime (void);
static hrtime_t gethrtime()
{
   return(clock_get_microsecs());
}
void sesut_ermi_r_fsmtest_print_timer_info (void)
{
    printf("\n\nThe execution times are in microseconds.");
    return;
}

#else 

/*
 * gethrtime() is not defined for this platform.
 * Create a stub.
 */
static hrtime_t gethrtime(void);
static hrtime_t gethrtime (void)
{
   return 0;
}
void sesut_ermi_r_fsmtest_print_timer_info (void)
{
    printf("\n\nThe mechanism to obtain timestamps is not available yet.");
    printf("\nAll entries for time would have zero's.");
    return;
}

#endif 



/* Utility functions */
static sesut_ermi_r_fsmtest_time sesut_ermi_r_fsmtest_gettimestamp(void);
static sesut_ermi_r_fsmtest_time sesut_ermi_r_fsmtest_getelapsedtime(sesut_ermi_r_fsmtest_time);
static ulong sesut_ermi_r_fsmtest_getfreememory(void);
static void sesut_ermi_r_fsmtest_gettestinfoblock(void);
static uint sesut_ermi_r_fsmtest_getfailurecount(boolean print_failmessage);
static void sesut_ermi_r_fsmtest_parser_init(void);
static void sesut_ermi_r_fsmtest_remove_parse(void);
static void sesut_ermi_r_fsmtest_globalsinit(void);

static void sesut_ermi_r_fsmtest_free_memory(void);
static void sesut_ermi_r_fsmtest_clear(void);

/* Used to create/maintain a queue of test information blocks */
static sesut_ermi_r_fsmtest_testinfo *sesut_ermi_r_fsmtest_listhead;
static sesut_ermi_r_fsmtest_testinfo *sesut_ermi_r_fsmtest_current;

/* The structure definition used by global sesut */
static sesut_testinfo testinfo;

static sesut_ermi_r_fsmtest_testresult_type sesut_ermi_r_fsmtest_default_result = SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN;

/*
 * sesut_ermi_r_fsmtest subsystem initialization 
 */
void sesut_ermi_r_fsmtest_init (subsystype *subsys)
{
    sesut_ermi_r_fsmtest_parser_init();
    sesut_ermi_r_fsmtest_globalsinit();
    sesut_ermi_r_fsmtest_memoryinit();

    /* Add pointers to various functions. */
    testinfo.unittest=sesut_ermi_r_fsmtest_api_defaultparams;
    testinfo.getstatus_fn=sesut_ermi_r_fsmtest_get_status;
    testinfo.setrepeat_fn=sesut_ermi_r_fsmtest_set_repeatcount;
    testinfo.clear_fn=sesut_ermi_r_fsmtest_clear;
    testinfo.settrace_fn=sesut_ermi_r_fsmtest_trace;

    testinfo.testName=sesut_ermi_r_fsmtest_test_name;
    testinfo.getfailurecount=sesut_ermi_r_fsmtest_getfailurecount;
    testinfo.removep=sesut_ermi_r_fsmtest_remove_parse;
    sesut_add_unittest(&testinfo,0); 
    
}

/*
 *	sesut_ermi_r_fsmtest_parser_init:
 *	Initialize the parser support for sesut_ermi_r_fsmtest
 */
static void sesut_ermi_r_fsmtest_parser_init (void)
{
    int rc = parser_add_commands(PARSE_ADD_EXEC_CMD,
		 &pname(sesut_ermi_r_fsmtest_exec_command), "sesut_ermi_r_fsmtest");
    if (rc == FALSE) {
	printf("\nSESUT-001E>" 
	       "parser_add_commands for 'sesut_ermi_r_fsmtest' failed\n");
    }
}

/*
 * sesut_ermi_r_fsmtest_remove_parse
 * Removes the parse chain for 'this' test (for DLST only)
 * also free memory used to store test data
 * calls user provided destructor 
 */    
static void sesut_ermi_r_fsmtest_remove_parse (void) {
    if (!system_isInitialized()) return;
    printf("\nSESUT: removing parse info sesut_ermi_r_fsmtest\n");
    if (!parser_delete_command_list(sesut_ermi_r_fsmtest_init_table, "sesut_ermi_r_fsmtest")) {
	printf("\nSESUT-002E>"
	       "parser_delete_command_list for'sesut_ermi_r_fsmtest' failed \n");
    }
    sesut_ermi_r_fsmtest_free_memory();
    
}  

/*
 *Function inializes the global variables
 */

static void sesut_ermi_r_fsmtest_globalsinit (void) {
    
    sesut_ermi_r_fsmtest_trace_status=SESUT_ERMI_R_FSMTEST_TRACE_OFF;
    sesut_ermi_r_fsmtest_last_index = 0;
    sesut_ermi_r_fsmtest_last_timestamp = 0;
    sesut_ermi_r_fsmtest_start_test = 0;
    sesut_ermi_r_fsmtest_default_repeatcount = 1;
    sesut_ermi_r_fsmtest_current_scalefactor = 1;

/* SESUT_ERMI_R_FSMTEST_MAX_BLOCKS can be defined using -D flag during compilation. */
#if defined(SESUT_ERMI_R_FSMTEST_MAX_BLOCKS)
    sesut_ermi_r_fsmtest_max_testinfo_blocks_defined = TRUE;
    sesut_ermi_r_fsmtest_max_testinfo_blocks=SESUT_ERMI_R_FSMTEST_MAX_BLOCKS;
#else
    sesut_ermi_r_fsmtest_max_testinfo_blocks_defined = FALSE;
    sesut_ermi_r_fsmtest_max_testinfo_blocks=SESUT_ERMI_R_FSMTEST_MAX_BLOCKS_DEFAULT;
#endif

    sesut_ermi_r_fsmtest_chunk = NULL;
    sesut_ermi_r_fsmtest_listhead = NULL;
    sesut_ermi_r_fsmtest_current = NULL;
    sesut_ermi_r_fsmtest_times_cli_used = 0;
    sesut_ermi_r_fsmtest_times_api_used = 0;
    sesut_ermi_r_fsmtest_times_defaultapi_used = 0;
    sesut_ermi_r_fsmtest_number_of_testinfo_blocks = 0;
}


/* Call this if and only if unit test is to be invoked before subsystem 
 * initialization but after memory management system is initialized.
 * sesut_ermi_r_fsmtest_memoryinit ensures that internal data structures
 * are ready.
 */
void sesut_ermi_r_fsmtest_memoryinit (void) {

    /* If chunk memory is already created then there is nothing to do. */
    if (sesut_ermi_r_fsmtest_chunk!=NULL) {
        return;
    }
    /* If in low memory mode do not create chunk memory. */
    if (sesut_ermi_r_fsmtest_max_testinfo_blocks_defined && 
          (sesut_ermi_r_fsmtest_max_testinfo_blocks==0)) {
        return;
    }
    if (sesut_ermi_r_fsmtest_chunk==NULL) {
        sesut_ermi_r_fsmtest_chunk=chunk_create(sizeof(sesut_ermi_r_fsmtest_testinfo),
                sesut_ermi_r_fsmtest_max_testinfo_blocks,CHUNK_FLAGS_DYNAMIC,
                NULL,0,"sesut_ermi_r_fsmtest local testinfo");
        if (sesut_ermi_r_fsmtest_chunk==NULL) {
            buginf("\nSESUT: sesut_ermi_r_fsmtest Chunk create failed");
            sesut_ermi_r_fsmtest_current=NULL;
            return;
        }
    }
}

/*
 * Function frees memory used to store test results
 */
static void sesut_ermi_r_fsmtest_free_memory (void) {

    sesut_ermi_r_fsmtest_testinfo *current,*next;
    uint res;

    current=sesut_ermi_r_fsmtest_listhead;
    while (current!=NULL) {
        next=(current->next);
        
        if (current->param1){
free(current->param1);
}
        chunk_free(sesut_ermi_r_fsmtest_chunk,current);
        current=next;
    }
    sesut_ermi_r_fsmtest_listhead=NULL;
    sesut_ermi_r_fsmtest_current=NULL;
    sesut_ermi_r_fsmtest_times_cli_used=0;
    sesut_ermi_r_fsmtest_times_api_used=0;
    sesut_ermi_r_fsmtest_times_defaultapi_used=0;
    sesut_ermi_r_fsmtest_number_of_testinfo_blocks=0;

    if (sesut_ermi_r_fsmtest_chunk != NULL) {
        res = chunk_destroy( sesut_ermi_r_fsmtest_chunk);
        if (!res) {
            printf("\nSESUT:error> Chunk:sesut_ermi_r_fsmtest_chunk: is not empty");
        }
    }
    sesut_ermi_r_fsmtest_chunk = NULL;
}

/* If test is dynamically loaded sesut subsystem is not initialized.*/
#ifndef SESUT_DLST
/*
 * sesut_ermi_r_fsmtest subsystem header
 */

#define SESUT_ERMI_R_FSMTEST_MAJVERSION 1
#define SESUT_ERMI_R_FSMTEST_MINVERSION 0
#define SESUT_ERMI_R_FSMTEST_EDITVERSION 1

SUBSYS_HEADER(sesut_ermi_r_fsmtest, SESUT_ERMI_R_FSMTEST_MAJVERSION, 
              SESUT_ERMI_R_FSMTEST_MINVERSION, SESUT_ERMI_R_FSMTEST_EDITVERSION,
	      sesut_ermi_r_fsmtest_init, SUBSYS_CLASS_KERNEL,
	      "seq:sesut");
#endif

/* Print status */
void sesut_ermi_r_fsmtest_status_parse (parseinfo* csb) {

   /* Check if we need to provide detailed information */
   if (GETOBJ(int,1)==0) {
       /* Check if we need to direct output to URL */
       if (strncmp(GETOBJ(string,1),"",1)==0) {
           sesut_ermi_r_fsmtest_status();
       } else {
           sesut_stdout_to_url(sesut_ermi_r_fsmtest_status,GETOBJ(string,1),
              SESUT_STDOUT_REDIRECT);
       }
   } else {
       /* Check if we need to direct output to URL */
       if (strncmp(GETOBJ(string,1),"",1)==0) {
           sesut_ermi_r_fsmtest_status_detailed();
       } else {
           sesut_stdout_to_url(sesut_ermi_r_fsmtest_status_detailed,GETOBJ(string,1),
              SESUT_STDOUT_REDIRECT);
       }
   }
}


/* Print status  - called from "globalsesut status" */
void sesut_ermi_r_fsmtest_get_status (boolean detailed, char *url) {
   /* Check if we need to provide detailed information */
   if (detailed) {
       /* Check if we need to direct output to URL */
       if (strncmp(url,"",1)==0) {
           sesut_ermi_r_fsmtest_status_detailed();
       } else {
           sesut_stdout_to_url(sesut_ermi_r_fsmtest_status_detailed,url,
              SESUT_STDOUT_APPEND);
       }
   } else {
       /* Check if we need to direct output to URL */
       if (strncmp(url,"",1)==0) {
           sesut_ermi_r_fsmtest_status();
       } else {
           sesut_stdout_to_url(sesut_ermi_r_fsmtest_status,url,
              SESUT_STDOUT_APPEND);
       }
   }
}


/*
 * This function prints information about
 * the unit test and the history of test executions.
 */
void sesut_ermi_r_fsmtest_status () {

    sesut_ermi_r_fsmtest_testinfo *current;
    uint block_count, test_count;

    if ((sesut_ermi_r_fsmtest_times_cli_used+sesut_ermi_r_fsmtest_times_api_used+
           sesut_ermi_r_fsmtest_times_defaultapi_used)>0) {
        if (sesut_ermi_r_fsmtest_listhead==NULL) {
            printf("\nsesut_ermi_r_fsmtest has been executed but there is no "
                   "log of activity.");
        } else {
            printf("\nsesut_ermi_r_fsmtest has been executed.");
        }
    } else {
        printf("\nsesut_ermi_r_fsmtest has not been executed.");
    }
    printf("\nUnit test description file is - %s","/vob/ios.sys7/sys/obj-sp-unixrp/ermi_r_fsmtest.sesut");
    if (testinfo.isDynamicLoaded) {
	printf("\nThis SESUT test is dynamically loaded");
	printf("\nThe current version is %u",testinfo.sesutVersion);
    }
    printf("\nModel used is - Digraph");
    if (sesut_ermi_r_fsmtest_dtd_availability) {
        printf("\nAPI robustness tests are available.");
    } else {
        printf("\nThere is no API robustness test.");
    }
    printf("\nDefault repeat count is -  %u",
        sesut_ermi_r_fsmtest_default_repeatcount);
    printf("\nThis test does not alter the global state.\nThis test can be executed under IOU.");
    printf("\nInitializer function is not specified.");
    printf("\nFinalizer function is not specified.");
    printf("\nPre-test function is not specified.");
    printf("\nPost-test function is not specified.");
    printf("\nPre-test function(with parameters) is not specified.");
    printf("\nPost-test function(with parameters) is not specified.");
    if (sesut_ermi_r_fsmtest_trace_status==SESUT_ERMI_R_FSMTEST_TRACE_ON) {
        printf("\nTrace is on.");
    } else {
        printf("\nTrace is off.");
    }

    if (sesutFlushLoggerAfterTest) {
   	printf("\nFlush logger is on.");
    } else {
	printf("\nFlush logger is off.");
    }
    
    printf("\nThe test has 1 parameter(s)."
        "\nInformation about parameter(s)(Parameter Variable Type Default):"
        "\n1 peer_addr addrtype* NULL"
        );

    printf("\nNumber of times invoked via CLI - %lu",
                                  sesut_ermi_r_fsmtest_times_cli_used);
    printf("\nNumber of times invoked via API - %lu",
                                  sesut_ermi_r_fsmtest_times_api_used);
    printf("\nNumber of times invoked via API(defaults) - %lu",
                                  sesut_ermi_r_fsmtest_times_defaultapi_used);
    printf("\nMaximum number of entries in the log - %u",
                                  sesut_ermi_r_fsmtest_max_testinfo_blocks);
    block_count=0;
    current=sesut_ermi_r_fsmtest_listhead;
    while (current!=NULL) {
        block_count++;
        current=current->next;
    }
    printf("\nNumber of entries in the log - %u",block_count);
    /* If we have no log then return. */
    if (sesut_ermi_r_fsmtest_listhead==NULL) {
        return;
    }

    sesut_ermi_r_fsmtest_print_timer_info();
    printf("\nUse caution in interpreting the time information.");
    printf("\nThese are elapsed times. Any activity on the system");
    printf("\nis included in the times reported. Repeat your tests.");

    /* Print summary statistics.*/
    printf("\n\nSummary statistics:");
    current=sesut_ermi_r_fsmtest_listhead;
    printf("\nRepeatcount:");
    while (current!=NULL) {
        printf(" %u",current->repeatcount);
        current=current->next;
    }
    current=sesut_ermi_r_fsmtest_listhead;
    printf("\nScalefactor:");
    while (current!=NULL) {
        printf(" %u",current->scalefactor);
        current=current->next;
    }
    current=sesut_ermi_r_fsmtest_listhead;
    printf("\nExecutiontime:");
    while (current!=NULL) {
        printf(" %lld",current->executiontime);
        current=current->next;
    }
    current=sesut_ermi_r_fsmtest_listhead;
    printf("\nMemory used(bytes):");
    while (current!=NULL) {
        printf(" %ld",current->memoryused);
        current=current->next;
    }
    current=sesut_ermi_r_fsmtest_listhead;
    printf("\nHow invoked:");
    while (current!=NULL) {
        if (current->howinvoked==SESUT_ERMI_R_FSMTEST_CLI_IN_USE) {
            printf(" CLI");
        } else if (current->howinvoked==SESUT_ERMI_R_FSMTEST_API_IN_USE) {
            printf(" API");
        } else if (current->howinvoked==SESUT_ERMI_R_FSMTEST_DEFAPI_IN_USE) {
            printf(" API(defaults)");
        } else {
            printf("\nInternal error - Unrecognized value for "
                   "how invoked.");
        }
        current=current->next;
    }
    current=sesut_ermi_r_fsmtest_listhead;
    test_count = 0;
    printf("\nTest result:");
    while (current!=NULL) {
    uint i;	
	test_count++;
        switch (current->testresult) {
        case SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN:
            printf("\n %u. Unknown", test_count);
            break;
        case SESUT_ERMI_R_FSMTEST_TEST_PASSED:
            printf("\n %u. Pass (%d passes/%d failures)", test_count,
	           current->count_of_passes, current->count_of_failures);
            break;
        case SESUT_ERMI_R_FSMTEST_TEST_FAILED:
     	    printf("\n %u. Fail (%d passes/%d failures)", test_count, 
	           current->count_of_passes, current->count_of_failures);
	        for (i=0;i<=current->count_of_failures&&i<MAX_FAIL_COUNT;i++) {
                sesut_output_failmessage(current->cause_for_failure[i],
                       255,
                       "     ",SESUT_OUTPUT_LINE_LEN);	        	
	        }   
            break;
        default:
            printf("\nInternal error - Unrecognized value for test result.");
        }
        current=current->next;
    }

    /* Print values of parameters. */
    printf("\n\nValue(s) of parameter(s):");
    current=sesut_ermi_r_fsmtest_listhead;
    printf("\npeer_addr");
    while (current!=NULL) {
        printf(" %i",current->param1->ip_addr);
        current=current->next;
    }

}


/*
 * This function prints detailed information about
 * the unit test.
 */
void sesut_ermi_r_fsmtest_status_detailed () {

    sesut_ermi_r_fsmtest_testinfo *current;
    uint index, test_count;
    uint next_column=7;

    /* First print the usual information. */
    sesut_ermi_r_fsmtest_status();

    /* If no test has been executed then nothing to print*/
    if (sesut_ermi_r_fsmtest_listhead==NULL) {
        return;
    }
    printf("\n\nFollowing table provides performance/scalability"
           " data\nthat can be exported to a data analysis program.");
    printf("\n\nWe are looking for a lightweight data analysis"
           " package\nthat can be included in SESUT images.");
    printf("\nColumn Heading");
    printf("\n------ -------");
    printf("\n1 repeatcount");
    printf("\n2 scalefactor");
    printf("\n3 executiontime");
    printf("\n4 memoryused");
    printf("\n5 howinvoked");
    printf("\n6 testresult");
    printf("\n%u Parameter peer_addr",next_column);
    next_column++;
    for (index=0;index<1;index++) {
        printf("\n%u %s(count)",next_column,
                sesut_ermi_r_fsmtest_graphLabels[index]);
        next_column++;
        printf("\n%u %s(time)",next_column,
                sesut_ermi_r_fsmtest_graphLabels[index]);
        next_column++;
    }
    printf("\n");

    current=sesut_ermi_r_fsmtest_listhead;
    test_count =0;
    while (current!=NULL) {
        test_count++;
        printf("\n%u",current->repeatcount);
        printf(" %u",current->scalefactor);
        printf(" %lld",current->executiontime);
        printf(" %ld",current->memoryused);
        if (current->howinvoked==SESUT_ERMI_R_FSMTEST_CLI_IN_USE) {
            printf(" CLI");
        } else if (current->howinvoked==SESUT_ERMI_R_FSMTEST_API_IN_USE) {
            printf(" API");
        } else if (current->howinvoked==SESUT_ERMI_R_FSMTEST_DEFAPI_IN_USE) {
            printf(" API(defaults)");
        } else {
            printf("\nInternal error - Unrecognized value for "
                   "how invoked.");
        }
        switch (current->testresult) {
        case SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN:
            printf(" Unknown");
            break;
        case SESUT_ERMI_R_FSMTEST_TEST_PASSED:
            printf(" Pass (%d passes/%d failures)",
            current->count_of_passes,current->count_of_failures);
            break;
        case SESUT_ERMI_R_FSMTEST_TEST_FAILED:
	        printf(" Fail (%d passes/%d failures)",
            current->count_of_passes,current->count_of_failures);
            break;
        default:
            printf("\nInternal error - Unrecognized value for "
                   "test result.\n");
        }
        printf(" %i",current->param1->ip_addr);
        for (index=0;index<1;index++) {
            printf(" %u %lld",current->nodes_and_edges[index].count,
                   current->nodes_and_edges[index].time);
        }
        current=current->next;
    }
}

/*
 * This function sets default repeat count
 */
void sesut_ermi_r_fsmtest_set_default_repeatcount (parseinfo* csb) {

    sesut_ermi_r_fsmtest_default_repeatcount=GETOBJ(int,6);
    printf("\nDone.");
}

/*
 * This function sets default repeat count 
 * Called via "globalsesut setrepeat"
 */
void sesut_ermi_r_fsmtest_set_repeatcount (uint repeatcount) {
    sesut_ermi_r_fsmtest_default_repeatcount=repeatcount;
}

/*
 * This function is invoked from parser in response to 'clear' command.
 */
void sesut_ermi_r_fsmtest_parse_clear (parseinfo* csb) {
    sesut_ermi_r_fsmtest_clear();
    printf("\nDone.");
}

/*
 * This function clears data structures
 * Could be invoked via CLI or API.
 * Free memory allocated to save string parameters.
 * Free test info. blocks.
 */
static void sesut_ermi_r_fsmtest_clear (void) {
    sesut_ermi_r_fsmtest_testinfo *current,*next;

    current=sesut_ermi_r_fsmtest_listhead;
    while (current!=NULL) {
        next=(current->next);
        
        if (current->param1){
free(current->param1);
}
        chunk_free(sesut_ermi_r_fsmtest_chunk,current);
        current=next;
    }
    sesut_ermi_r_fsmtest_listhead=NULL;
    sesut_ermi_r_fsmtest_current=NULL;
    sesut_ermi_r_fsmtest_times_cli_used=0;
    sesut_ermi_r_fsmtest_times_api_used=0;
    sesut_ermi_r_fsmtest_times_defaultapi_used=0;
    sesut_ermi_r_fsmtest_number_of_testinfo_blocks=0;
    sesut_ermi_r_fsmtest_dtd_all=FALSE;
    sesut_ermi_r_fsmtest_dtd_singlefn=FALSE;
    sesut_ermi_r_fsmtest_dtd_notest=FALSE;
}

/*
 * Start of test action
 */
void sesut_ermi_r_fsmtest_startoftest (void) {
    sesut_ermi_r_fsmtest_start_test=SESUT_ERMI_R_FSMTEST_THISIS_FIRSTNODE;
    if (sesut_ermi_r_fsmtest_trace_status==SESUT_ERMI_R_FSMTEST_TRACE_ON) {
        buginf("\nSESUT: sesut_ermi_r_fsmtest start of graph trace");
    }
}

/*
 * End of test action
 */
void sesut_ermi_r_fsmtest_endoftest (void) {
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->
            nodes_and_edges[sesut_ermi_r_fsmtest_last_index].time+=
            sesut_ermi_r_fsmtest_getelapsedtime(sesut_ermi_r_fsmtest_last_timestamp);
    }
    if (sesut_ermi_r_fsmtest_trace_status==SESUT_ERMI_R_FSMTEST_TRACE_ON) {
        buginf("\nSESUT: sesut_ermi_r_fsmtest end of graph trace");
    }
}


/*
 * Get the timestamp 
 */
sesut_ermi_r_fsmtest_time sesut_ermi_r_fsmtest_gettimestamp (void) {
    return gethrtime();
}

/*
 * Get the elapsed time 
 */
static sesut_ermi_r_fsmtest_time sesut_ermi_r_fsmtest_getelapsedtime (sesut_ermi_r_fsmtest_time starttime) {
    sesut_ermi_r_fsmtest_time end_time;
    sesut_ermi_r_fsmtest_time  sesut_ermi_r_fsmtest_elapsed_time;
    end_time = gethrtime();

#if defined(__mips) || defined(__mip64)  || defined(__PPC)
    if (end_time < starttime) {
	 sesut_ermi_r_fsmtest_elapsed_time = (end_time + (( 0xffffffff - starttime) + 1));
        return (sesut_ermi_r_fsmtest_elapsed_time);
    }
#endif
    sesut_ermi_r_fsmtest_elapsed_time = (end_time-starttime);
    return (sesut_ermi_r_fsmtest_elapsed_time);
}

/*
 * Get the size of available memory on the box
 */

static ulong sesut_ermi_r_fsmtest_getfreememory (void) {

    mempool_class class;
    mempool *pool;
    ulong total_size_bytes = 0;

    FOR_ALL_MEMPOOLS(pool, class) {
        if (!pool || (pool->class != class))
            continue;
        if (pool->class == MEMPOOL_CLASS_LOCAL) {
            total_size_bytes += (2*pool->size);
        }
    }
    return total_size_bytes;	
}

/*
 * Enable tracing of nodes and edges traversed using CLI
 */
void sesut_ermi_r_fsmtest_parse_traceon (parseinfo* csb) {
    if (sesut_ermi_r_fsmtest_traceon()==FALSE) {
        printf("\nTrace is already enabled.");
    } else {
        printf("\nTrace is enabled.");
    }
}

/*
 * Disable tracing of nodes and edges traversed using CLI
 */
void sesut_ermi_r_fsmtest_parse_traceoff (parseinfo* csb) {
    if (sesut_ermi_r_fsmtest_traceoff()==FALSE) {
        printf("\nTrace is already disabled.");
    } else {
        printf("\nTrace is disabled.");
    }
}

/*
 * Enable/Disable tracing of nodes and edges traversed 
 * Called from "globalsesut trace"
 */
void sesut_ermi_r_fsmtest_trace (boolean trace) {
    if (trace) {
        sesut_ermi_r_fsmtest_parse_traceon(NULL);
    } else {
        sesut_ermi_r_fsmtest_parse_traceoff(NULL);
    }
}

/*
 * Enable tracing of nodes and edges traversed using API
 */
boolean sesut_ermi_r_fsmtest_traceon (void) {
    if (sesut_ermi_r_fsmtest_trace_status==SESUT_ERMI_R_FSMTEST_TRACE_ON) {
        return FALSE;
    } else {
        sesut_ermi_r_fsmtest_trace_status=SESUT_ERMI_R_FSMTEST_TRACE_ON;
        return TRUE;
    }
}

/*
 * Disable tracing of nodes and edges traversed using API
 */
boolean sesut_ermi_r_fsmtest_traceoff (void) {
    if (sesut_ermi_r_fsmtest_trace_status==SESUT_ERMI_R_FSMTEST_TRACE_OFF) {
        return FALSE;
    } else {
        sesut_ermi_r_fsmtest_trace_status=SESUT_ERMI_R_FSMTEST_TRACE_OFF;
        return TRUE;
    }
}


/* Call sesut_ermi_r_fsmtest_testpass to indicate test success.*/
void sesut_ermi_r_fsmtest_testpass (void) {
    if (sesut_ermi_r_fsmtest_current!=NULL) {
    	sesut_ermi_r_fsmtest_current->count_of_passes++;
        if (sesut_ermi_r_fsmtest_current->testresult==SESUT_ERMI_R_FSMTEST_TEST_FAILED) {
        	return;
        } else {
            sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_PASSED;
            if (sesut_global_log_result) {
                buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest passed");
            }
        }
    }
}

/* Call sesut_ermi_r_fsmtest_testfail to indicate test failure.
 * The length of the formatted string should be less than or equal 
 * to 255.Else it will be 
 * truncated.
 */
void sesut_ermi_r_fsmtest_testfail (const char *fmt, ...) {

    va_list ap;
    int count;
    int fail_count;

    /* Record only the first MAX_FAIL_COUNT fail messages. */
    if (sesut_ermi_r_fsmtest_current!=NULL) {
    	fail_count = sesut_ermi_r_fsmtest_current->count_of_failures++;
        sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_FAILED;
        if (fail_count < MAX_FAIL_COUNT) {
            va_start(ap, fmt);
            /* vsnprintf in IOS does not return -1 for error.. */
            count = vsnprintf(sesut_ermi_r_fsmtest_current->
                 cause_for_failure[fail_count],
                 255, fmt, ap);
            sesut_ermi_r_fsmtest_current->cause_for_failure[fail_count][count] = '\0';
            va_end(ap);
        } else {
            buginf("\nSESUT log: Buffer full: Only first %d failure messages are logged.",
            MAX_FAIL_COUNT);	
        }
        if (sesut_global_log_result) {
            buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest failed - %s",
            sesut_ermi_r_fsmtest_current->
              cause_for_failure[sesut_ermi_r_fsmtest_current->count_of_failures]);
        }
    }
}


/*
 * Allocate a testifo block.
 * Set current block to the new block. This could be NULL.
 * If allocation fails after list is establishes(has atleast one
 * element) then the list is made into a circular list.
 * If we hit the limit on the number of blocks after list is 
 * establishes(has atleast one element) then the list is made into 
 * a circular list.
 */
void sesut_ermi_r_fsmtest_gettestinfoblock (void) {
    void *newblock;

    if (sesut_ermi_r_fsmtest_max_testinfo_blocks_defined && 
          (sesut_ermi_r_fsmtest_max_testinfo_blocks==0)) {
        sesut_ermi_r_fsmtest_current=NULL;
        return;
    }
    /* Check if we reached the limit on number of blocks */
    if (sesut_ermi_r_fsmtest_max_testinfo_blocks_defined && 
                (sesut_ermi_r_fsmtest_number_of_testinfo_blocks==
                  sesut_ermi_r_fsmtest_max_testinfo_blocks)) {
        /* We can't add any more blocks. Reached the limit. 
         * Let us make our list into a circular list.
         * This should work even if we already have a circular list.
         * Should work even if the max is 1.
         */
        sesut_ermi_r_fsmtest_current->next=sesut_ermi_r_fsmtest_listhead;
        sesut_ermi_r_fsmtest_current=sesut_ermi_r_fsmtest_listhead;
        sesut_ermi_r_fsmtest_listhead=sesut_ermi_r_fsmtest_listhead->next;
        bzero(sesut_ermi_r_fsmtest_current,sizeof(sesut_ermi_r_fsmtest_testinfo));
        return;
    }
    /* Create chunk if needed */
    sesut_ermi_r_fsmtest_memoryinit();
    if (sesut_ermi_r_fsmtest_chunk==NULL) {
        sesut_ermi_r_fsmtest_current=NULL;
        return;
    }
    /* Let us try to get a block of memory */
    newblock=chunk_malloc(sesut_ermi_r_fsmtest_chunk);
    if (newblock!=NULL) {
        if (sesut_ermi_r_fsmtest_listhead==NULL) {
            sesut_ermi_r_fsmtest_listhead=newblock; 
        } else {
            sesut_ermi_r_fsmtest_current->next=newblock;
        }
        sesut_ermi_r_fsmtest_current=newblock;
        sesut_ermi_r_fsmtest_number_of_testinfo_blocks++;
        return;
    } else {
        buginf("\nSESUT: sesut_ermi_r_fsmtest Chunk malloc failed");
        if (sesut_ermi_r_fsmtest_number_of_testinfo_blocks==0) {
            sesut_ermi_r_fsmtest_current=NULL;
            return;
        }
        /* We cant add any more blocks. Let us make our list
         * into a circular list.
         */
        sesut_ermi_r_fsmtest_current->next=sesut_ermi_r_fsmtest_listhead;
        sesut_ermi_r_fsmtest_current=sesut_ermi_r_fsmtest_listhead;
        sesut_ermi_r_fsmtest_listhead=sesut_ermi_r_fsmtest_listhead->next;
        bzero(sesut_ermi_r_fsmtest_current,sizeof(sesut_ermi_r_fsmtest_testinfo));
        return;
    }
}

/* Return the number of failures. Optionally print the failure
 * messages.
 */
static uint sesut_ermi_r_fsmtest_getfailurecount (boolean print_failuremessage) {
    uint failure_count;
    uint i;
    sesut_ermi_r_fsmtest_testinfo *current;

    failure_count=0;
    current=sesut_ermi_r_fsmtest_listhead;
    while (current!=NULL) {
        if (current->testresult==SESUT_ERMI_R_FSMTEST_TEST_FAILED) {
            failure_count++;
            if (print_failuremessage) {
                printf(" Test sesut_ermi_r_fsmtest failed  -\n");
                for (i=0;i<=current->count_of_failures&&i<MAX_FAIL_COUNT;i++) {
                    sesut_output_failmessage(current->cause_for_failure[i],
                       255,
                       "     ",SESUT_OUTPUT_LINE_LEN);                	
                }
            }
        }
        current=(current->next);
    }
    return failure_count;
}

/*
 * This function drives the unit test.
 * Receives the inputs via CLI.
 */
void sesut_ermi_r_fsmtest_harness (parseinfo *csb) {

    sesut_ermi_r_fsmtest_time starttime;
    ulong start_freememory;
    sesut_ermi_r_fsmtest_time sesut_current_executiontime;
    uint sesut_current_memoryused;
    
    boolean perform_gd,perform_mif,get_cflow,sesut_gdmifcflow_result;

    printf("\nExecuting unit test %s","sesut_ermi_r_fsmtest");
    /* If user has not entered values for parameters then use defaults. */
    if (GETOBJ(int,5)==SESUT_ERMI_R_FSMTEST_USE_PARAM_DEFAULTS) {
        printf("\nUsing default values for parameters.");
        SETOBJ(paddr,1) = dummyaddr;
    }


    /* Determine the repeat count */
    if (GETOBJ(int,1)==SESUT_ERMI_R_FSMTEST_REPEAT_SPECIFIED) {
        sesut_ermi_r_fsmtest_current_repeatcount=GETOBJ(int,2);
        printf("\nTest will be repeated %u time(s).",
              sesut_ermi_r_fsmtest_current_repeatcount);
    } else {
        sesut_ermi_r_fsmtest_current_repeatcount=sesut_ermi_r_fsmtest_default_repeatcount;
        printf("\nRepeat count is not specified. Test will be "
               "executed %u time(s).",sesut_ermi_r_fsmtest_default_repeatcount);
    }

    /* Determine the scale factor */
    if (GETOBJ(int,3)==SESUT_ERMI_R_FSMTEST_SCALE_SPECIFIED) {
        sesut_ermi_r_fsmtest_current_scalefactor=GETOBJ(int,4);
        printf("\nScale factor is %u", sesut_ermi_r_fsmtest_current_scalefactor);
    } else {
        sesut_ermi_r_fsmtest_current_scalefactor=1;
        printf("\nScale factor is not specified. Assumed to be 1.");
    }

    /* Start GD,MIF and Cflow */
    if (GETOBJ(int,6)==SESUT_ERMI_R_FSMTEST_GD_SPECIFIED) {
        perform_gd=TRUE;
        sesut_gdmifcflow_result =
         sesut_execcommand(TRUE,"set memory debug incremental starting-time");
        if (!sesut_gdmifcflow_result) {
            printf("\nSESUT: set mem debug incremental starting-time "
                   "- not recognized");
            printf("\nSESUT: gd option ignored.");
            perform_gd=FALSE;
        }
    } else {
        perform_gd=FALSE;
    }
    if (GETOBJ(int,7)==SESUT_ERMI_R_FSMTEST_MIF_SPECIFIED) {
        perform_mif=TRUE;
        sesut_gdmifcflow_result = sesut_execcommand(TRUE,"mif on");
        if (!sesut_gdmifcflow_result) {
            printf("\nSESUT: mif on - not recognized");
            printf("\nSESUT: mif option ignored.");
            perform_mif=FALSE;
        }
    } else {
        perform_mif=FALSE;
    }
    if (GETOBJ(int,8)==SESUT_ERMI_R_FSMTEST_GCOV_SPECIFIED) {
        get_cflow=TRUE;
    } else {
        get_cflow=FALSE;
    }

    /* Print the values of parameters*/
    printf("\nValue(s) of parameter(s):");
    printf("\npeer_addr=%i",
      GETOBJ(paddr,1)->ip_addr);


    /* Let the output from the test begin on new line*/
    printf("\n");

    starttime=sesut_ermi_r_fsmtest_gettimestamp();
    start_freememory=sesut_ermi_r_fsmtest_getfreememory();

    /* This block will be used during the test to record count/time
     * for nodes/edges.
     */
    sesut_ermi_r_fsmtest_gettestinfoblock();
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN;
    }

    printf("Start Execution \n");
    if (sesut_global_log_startend) {
        buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest started(CLI)");
    }
    sesut_global_current_testpass_fn=sesut_ermi_r_fsmtest_testpass;
    sesut_global_current_testfail_fn=sesut_ermi_r_fsmtest_testfail;

    
    
    /* Execute the test */
    for (sesut_ermi_r_fsmtest_current_repeatindex=0;
        sesut_ermi_r_fsmtest_current_repeatindex<sesut_ermi_r_fsmtest_current_repeatcount;
              sesut_ermi_r_fsmtest_current_repeatindex++) {
        if (sesut_ermi_r_fsmtest_dtd_notest==FALSE) {
            sesut_ermi_r_fsmtest(GETOBJ(paddr,1));
        }
        if (sesut_ermi_r_fsmtest_dtd_all||sesut_ermi_r_fsmtest_dtd_singlefn) {
            sesut_ermi_r_fsmtest_dtd_exec_tests();
        }
    }
    sesut_ermi_r_fsmtest_dtd_all=FALSE;
    sesut_ermi_r_fsmtest_dtd_singlefn=FALSE;
    sesut_ermi_r_fsmtest_dtd_notest=FALSE;
    sesut_global_current_testpass_fn=NULL;
    sesut_global_current_testfail_fn=NULL;
    
    
    sesut_current_executiontime=
                   sesut_ermi_r_fsmtest_getelapsedtime(starttime);
    sesut_current_memoryused=start_freememory-sesut_ermi_r_fsmtest_getfreememory();

    /* If we have a test information block, fill the block. */
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->repeatcount=sesut_ermi_r_fsmtest_current_repeatcount;
        sesut_ermi_r_fsmtest_current->scalefactor=sesut_ermi_r_fsmtest_current_scalefactor;
        sesut_ermi_r_fsmtest_current->executiontime=sesut_current_executiontime;
        sesut_ermi_r_fsmtest_current->memoryused=sesut_current_memoryused;
        sesut_ermi_r_fsmtest_current->howinvoked=SESUT_ERMI_R_FSMTEST_CLI_IN_USE;
        
        /* Copy the string to testinfo block*/
        sesut_ermi_r_fsmtest_current->param1=malloc_named(sizeof(addrtype*),"sesut_ermi_r_fsmtest paddr 1");
        if (sesut_ermi_r_fsmtest_current->param1==NULL) {
            printf("\nCouldn't allocate memory to save unit test param string.\n");
        } else {
            *sesut_ermi_r_fsmtest_current->param1= *GETOBJ(paddr,1);
        }
	

        /* Save uint parameters */
        
    }
    sesut_ermi_r_fsmtest_times_cli_used++;

    if (perform_gd) {
        sesut_gdmifcflow_result=
          sesut_execcommand(TRUE,"show memory debug incremental leaks");
        if (!sesut_gdmifcflow_result) {
            printf("\nSESUT: show mem incremental leaks - not recognized");
        }
    }
    if (perform_mif) {
        sesut_gdmifcflow_result=sesut_execcommand(TRUE,"mif off");
        if (!sesut_gdmifcflow_result) {
            printf("\nSESUT: mif off - not recognized");
        }
    }
    if (get_cflow) {
        sesut_gdmifcflow_result=sesut_execcommand(TRUE,"cflow fastcopy");
        if (!sesut_gdmifcflow_result) {
            printf("\nSESUT: cflow fastcopy - not recognized");
        }
        sesut_gdmifcflow_result=sesut_execcommand(TRUE,"cflow listfiles 0");
        if (!sesut_gdmifcflow_result) {
            printf("\nSESUT: cflow listfiles 0 - not recognized");
        }
    }

    /* if the logger flush option is chosen, flush the log */
    if (sesutFlushLoggerAfterTest) {
	sesut_logger_flush();
    }

    switch (sesut_ermi_r_fsmtest_current->testresult) {
        case SESUT_ERMI_R_FSMTEST_TEST_PASSED:
            printf("\nUnit test %s passed (%d passes/%d failures)",
            "sesut_ermi_r_fsmtest",sesut_ermi_r_fsmtest_current->count_of_passes,
            sesut_ermi_r_fsmtest_current->count_of_failures);
            break;
        case SESUT_ERMI_R_FSMTEST_TEST_FAILED:
            printf("\nUnit test %s failed (%d passes/%d failures)",
            "sesut_ermi_r_fsmtest",sesut_ermi_r_fsmtest_current->count_of_passes,
            sesut_ermi_r_fsmtest_current->count_of_failures);
            break;
        case SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN:
            switch (sesut_ermi_r_fsmtest_default_result) {
            case SESUT_ERMI_R_FSMTEST_TEST_PASSED:
                sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_PASSED;
                printf("\nUnit test %s passed (default)","sesut_ermi_r_fsmtest");
                break;
            case SESUT_ERMI_R_FSMTEST_TEST_FAILED:
                sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_FAILED;
                printf("\nUnit test %s failed (default)","sesut_ermi_r_fsmtest");
                break;        
            default:
                printf("\nUnit test %s result is not known","sesut_ermi_r_fsmtest");
                break;
            }
            break;
        default:
            printf("\nInternal error - Unrecognized test result "
                   "for %s.","sesut_ermi_r_fsmtest");
    }
    printf("\nExecuted unit test %s","sesut_ermi_r_fsmtest");
    if (sesut_global_log_startend) {
        buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest ended(CLI)");
    }
}

/*
 * This function drives the unit test.
 * Call this function to execute the test.
 * We need to create testinfo block and save information.
 */
void sesut_ermi_r_fsmtest_api (addrtype* peer_addr) {

    sesut_ermi_r_fsmtest_time starttime;
    ulong start_freememory;
    sesut_ermi_r_fsmtest_time sesut_current_executiontime;
    uint sesut_current_memoryused;

    sesut_ermi_r_fsmtest_current_repeatcount=sesut_ermi_r_fsmtest_default_repeatcount;
    sesut_ermi_r_fsmtest_current_scalefactor=1;
    starttime=sesut_ermi_r_fsmtest_gettimestamp();
    if (sesut_global_log_startend) {
        buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest started(API)");
    }
    start_freememory=sesut_ermi_r_fsmtest_getfreememory();

    /* This block will be used during the test to record count/time
     * for nodes/edges.
     */
    sesut_ermi_r_fsmtest_gettestinfoblock();
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN;
    }
    sesut_global_current_testpass_fn=sesut_ermi_r_fsmtest_testpass;
    sesut_global_current_testfail_fn=sesut_ermi_r_fsmtest_testfail;

    
    
    /* Execute the test */
    for (sesut_ermi_r_fsmtest_current_repeatindex=0;
        sesut_ermi_r_fsmtest_current_repeatindex<sesut_ermi_r_fsmtest_current_repeatcount;
              sesut_ermi_r_fsmtest_current_repeatindex++) {
        sesut_ermi_r_fsmtest(peer_addr);
    }
    sesut_global_current_testpass_fn=NULL;
    sesut_global_current_testfail_fn=NULL;
    
    
    sesut_current_executiontime=
                   sesut_ermi_r_fsmtest_getelapsedtime(starttime);
    sesut_current_memoryused=start_freememory-sesut_ermi_r_fsmtest_getfreememory();

    /* If we have a test information block, fill the block. */
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->repeatcount=sesut_ermi_r_fsmtest_current_repeatcount;
        sesut_ermi_r_fsmtest_current->scalefactor=sesut_ermi_r_fsmtest_current_scalefactor;
        sesut_ermi_r_fsmtest_current->executiontime=sesut_current_executiontime;
        sesut_ermi_r_fsmtest_current->memoryused=sesut_current_memoryused;
        sesut_ermi_r_fsmtest_current->howinvoked=SESUT_ERMI_R_FSMTEST_API_IN_USE;
        /* Save uint parameters */
        
        /* String parameters are not saved. We can't allocate memory
         * here because this function could be invoked in interrupt
         * context. We can't use the same locations used in parameters
         * because when we try to use the pointers(during status)
         * the memory may have been freed(and possibly reallocated).
         */
    }
    if (sesut_global_log_startend) {
        buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest ended(API)");
    }
    sesut_ermi_r_fsmtest_times_api_used++;
    /* if the logger flush option is chosen, flush the log */
    if (sesutFlushLoggerAfterTest) {
	sesut_logger_flush();
    }
}

/*
 * This function executes the unit test using default values
 * for parameters.
 * We need to create testinfo block and save information.
 */
void sesut_ermi_r_fsmtest_api_defaultparams (sesut_repeat_scale_info 
                   *repeat_scale_data) {
    sesut_ermi_r_fsmtest_time starttime;
    ulong start_freememory;
    sesut_ermi_r_fsmtest_time sesut_current_executiontime;
    uint sesut_current_memoryused;

    if (repeat_scale_data->isScaleSpecified) {
        sesut_ermi_r_fsmtest_current_scalefactor=repeat_scale_data->scalefactor;
    } else {
        sesut_ermi_r_fsmtest_current_scalefactor=1;
    }
    if (sesut_global_log_startend) {
        buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest started(API defaults)");
    }
    starttime=sesut_ermi_r_fsmtest_gettimestamp();
    start_freememory=sesut_ermi_r_fsmtest_getfreememory();
    /* This block will be used during the test to record count/time
     * for nodes/edges.
     */
    sesut_ermi_r_fsmtest_gettestinfoblock();
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->testresult=SESUT_ERMI_R_FSMTEST_TEST_RESULT_UNKNOWN;
    }
    if (repeat_scale_data->isRepeatSpecified) {
        sesut_ermi_r_fsmtest_current_repeatcount=repeat_scale_data->repeatcount;
    } else {
        sesut_ermi_r_fsmtest_current_repeatcount=sesut_ermi_r_fsmtest_default_repeatcount;
    }
    sesut_global_current_testpass_fn=sesut_ermi_r_fsmtest_testpass;
    sesut_global_current_testfail_fn=sesut_ermi_r_fsmtest_testfail;

    
    
    /* Execute the test */
    for (sesut_ermi_r_fsmtest_current_repeatindex=0;
         sesut_ermi_r_fsmtest_current_repeatindex<sesut_ermi_r_fsmtest_current_repeatcount;
              sesut_ermi_r_fsmtest_current_repeatindex++) {
        sesut_ermi_r_fsmtest(NULL);
    }
    sesut_global_current_testpass_fn=NULL;
    sesut_global_current_testfail_fn=NULL;
    
    
    sesut_current_executiontime=
                   sesut_ermi_r_fsmtest_getelapsedtime(starttime);
    sesut_current_memoryused=start_freememory-sesut_ermi_r_fsmtest_getfreememory();

    /* If we have a test information block, fill the block. */
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->repeatcount=sesut_ermi_r_fsmtest_current_repeatcount;
        sesut_ermi_r_fsmtest_current->scalefactor=sesut_ermi_r_fsmtest_current_scalefactor;
        sesut_ermi_r_fsmtest_current->executiontime=sesut_current_executiontime;
        sesut_ermi_r_fsmtest_current->memoryused=sesut_current_memoryused;
        sesut_ermi_r_fsmtest_current->howinvoked=SESUT_ERMI_R_FSMTEST_DEFAPI_IN_USE;
        /* Save uint parameters */
        
        /* String parameters are not saved. We can't allocate memory
         * here because this function could be invoked in interrupt
         * context. We can't use the same locations used in parameters
         * because when we try to use the pointers(during status)
         * the memory may have been freed(and possibly reallocated).
         */
    }
    if (sesut_global_log_startend) {
        buginf("\nSESUT Log: Test sesut_ermi_r_fsmtest ended(API defaults)");
    }
    sesut_ermi_r_fsmtest_times_defaultapi_used++;

    /* if the logger flush option is chosen, flush the log */
    if (sesutFlushLoggerAfterTest) {
	sesut_logger_flush();
    }
}


/*
 * If trace is on print the node/edge just entered. 
 * If not the first node increment the time for the last
 * node/edge.
 */
void sesut_ermi_r_fsmtest_graph_entry_action (uint index) {
    if (sesut_ermi_r_fsmtest_trace_status==SESUT_ERMI_R_FSMTEST_TRACE_ON) {
        buginf("\nSESUT: sesut_ermi_r_fsmtest - Entering %s",
                     sesut_ermi_r_fsmtest_graphLabels[index]);
    }
    if (sesut_ermi_r_fsmtest_current!=NULL) {
        sesut_ermi_r_fsmtest_current->nodes_and_edges[index].count++;
    }
    if (sesut_ermi_r_fsmtest_start_test==SESUT_ERMI_R_FSMTEST_THISIS_FIRSTNODE) {
        sesut_ermi_r_fsmtest_start_test=SESUT_ERMI_R_FSMTEST_THISISNOT_FIRSTNODE;
    } else {
        if (sesut_ermi_r_fsmtest_current!=NULL) {
            sesut_ermi_r_fsmtest_current->
                nodes_and_edges[sesut_ermi_r_fsmtest_last_index].time+=
                sesut_ermi_r_fsmtest_getelapsedtime(sesut_ermi_r_fsmtest_last_timestamp);
        }
    }
    sesut_ermi_r_fsmtest_last_index=index;
    sesut_ermi_r_fsmtest_last_timestamp=sesut_ermi_r_fsmtest_gettimestamp();
}

/* DTD - Execute tests for all functions or a single function.
 * Write a message to the log before execution of the tests.
 */
void sesut_ermi_r_fsmtest_dtd_exec_tests() {
    char timestamp[CURRENT_TIME_STRING_MINBUF];
    char *dtd_all_message=" DTD(all) started
";
    char *dtd_single_message=" DTD(fn) started
";
    

    if (sesut_ermi_r_fsmtest_dtd_availability==FALSE) {
        printf("\nSESUT: Error - DTD is not used in sesut_ermi_r_fsmtest");
    }
    printf("\nSESUT(DTD) StartId - %lld, NextId - %lld and EndId - %lld",
            sesut_ermi_r_fsmtest_dtd_start,sesut_ermi_r_fsmtest_dtd_next,
            sesut_ermi_r_fsmtest_dtd_end);
    current_time_string(timestamp);
    sesut_dtdtestlog_write(timestamp,strlen(timestamp));
    if (sesut_ermi_r_fsmtest_dtd_all) {
        printf("\nSESUT(DTD all) Inter-test delay is %d seconds",
                     sesut_ermi_r_fsmtest_dtd_all_delay);
        sesut_dtdtestlog_write(dtd_all_message,strlen(dtd_all_message));
        
    } else {
        sesut_dtdtestlog_write(dtd_single_message,strlen(dtd_single_message));
        switch (sesut_ermi_r_fsmtest_dtd_fnid) {
            
            default: printf("\nSESUT - sesut_ermi_r_fsmtest Internal error - "
                       "Unrecognized DTD function code %d.",
                       sesut_ermi_r_fsmtest_dtd_fnid);
        }
    }
}

