#! /bin/csh

rm /vob/ios.comp/rfgw/lc/objects/qnx.ppc.8500/*
rm /vob/ios.comp/rfgw/lc/objects/qnx.ppc.8500.pic/*
rm /vob/ios.comp/rfgw/lc/objects/qnx.ppc.p4080/*
rm /vob/ios.comp/rfgw/lc/mv/objects/qnx.ppc.8500/*
rm /vob/ios.comp/rfgw/lc/mv/objects/qnx.ppc.8500.pic/*
rm /vob/ios.comp/rfgw/lc/tcc/objects/qnx.ppc.8500/*
rm /vob/ios.comp/rfgw/lc/tcc/objects/qnx.ppc.8500.pic/*
rm /vob/ios.comp/rfgw/lc/ds384/objects/qnx.ppc.p4080/*
rm /vob/ios.comp/rfgw/lc/ds384/objects/qnx.ppc.p4080.pic/*
