#! /bin/csh

setenv QNXLM_LICENSE_FILE @friday.cisco.com:@dechen-ultra5.cisco.com
setenv QNX_CONFIGURATION $HOME/qnx_license
setenv QNX_TARGET /auto/sjc_qnx_sdk/6.3.2/target/qnx6
setenv QNX_HOST /auto/sjc_qnx_sdk/6.3.2/host/linux/x86
setenv QCONFIG $QNX_TARGET/usr/include/qconfig.mk
setenv MKFILES_ROOT $QNX_TARGET/usr/include/mk/qtargets.mk
setenv SES_STATIC_ENV MISC
setenv SESTOOLS_NO_SESCPP 1

set comp = "/auto/sjc_qnx_sdk/6.3.2/host/linux/x86/usr/bin/qcc -V gcc_ntoppcbe -Wp,-simplify-pathnames -nostdinc -DTOOLS_VER=c2.95.3-p11b -DCOMPONENT_BUILD -DPARENT_COMPONENT=rfgw -D__QNX__ -DTARGET_CISCO -DOBJECT_8500 -Wp,-imacros -Wp,/vob/cisco.comp/make-lib/preinclude_macros.h -I/vob/cisco.comp -I/vob/ios/sys/h/iosinc -I/vob/ios/sys -I/auto/rfgw/qnx/6.3.2A/target/qnx6/usr/include -I/vob/ios/sys/h -I/auto/rfgw/qnx/6.3.2A/target/qnx6/usr/include -pipe -Wp,-simplify-pathnames -Wall -Wno-main -Wpointer-arith -Wstrict-prototypes -Wformat -Werror -O3 -DMPC8548_EVAL -Wno-strict-prototypes -Wp,-MD"

/auto/ses/bin/sacc -nonios -compiler $comp -no_sescpp -f $1

